### PR TITLE
some fixes.

### PR DESCRIPTION
**Pull request by btuduri**
Hello @lclevy ,

I fixed some non blocking warnings to normalize with the rest of the code.

I'm proposing to build your code with cmake in a complement with your makefile.

Regards,

### CODE REVIEW

**Comment by lclevy** [comment]
now part of OpenMPT
https://source.openmpt.org/svn/openmpt/trunk/OpenMPT/soundlib/Load_mo3.cpp
would it be better to directly contribute to OpenMPT ?

**Review by lclevy — APPROVED** [review]

**Review by lclevy — APPROVED** [review]

**Comment by btuduri** [comment]
Oh, I did not know, thanks for the information. 👍

**Comment by sagamusix** [comment]
> would it be better to directly contribute to OpenMPT ?

I don't really think there is anything specific that can be contributed, given that OpenMPT's MO3 loader is 100% feature-complete and only the decompression routes are taken from unmo3 (but slightly modified). I see some educational use in unmo3 but as I've said before, it really shouldn't be used in productive ways since there is little to no input sanitization - which is okay for a demonstrational tool, but not for something that is supposed to load arbitrary files. I think the decompression routines still rely on some undefined behaviour in C, which was fixed in OpenMPT long ago, I should probably re-apply those patches to unmo3 before someone copies the routines (Edit: Done now).

**Comment by btuduri** [comment]
it's heard :)

**Comment by lclevy** [comment]
I totally agree Sagamusix comments

**Pull request merged**
